// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygmharbfawtkwwcflzui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlnbWhhcmJmYXd0a3d3Y2ZsenVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc4ODk1NTEsImV4cCI6MjA3MzQ2NTU1MX0.eToCW6OIe2_ABl9cdtnn9syvhs7-QsRQ2RqRV2E78jU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});